name: Detect Package Changes

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for comparing changes

      - name: Detect changed directories with pkg.yaml
        id: detect-changes
        run: |
          # Make script executable
          chmod +x .github/scripts/detect-changes.sh
          
          # Determine the appropriate refs based on event type
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            # For pull requests, compare the PR base to the PR head
            FROM_REF="${{ github.event.pull_request.base.sha }}"
            TO_REF="${{ github.event.pull_request.head.sha }}"
          else
            # For pushes, use the before and after commit SHAs
            FROM_REF="${{ github.event.before }}"
            TO_REF="${{ github.event.after }}"
          fi
          
          # Run the detection script
          .github/scripts/detect-changes.sh "$FROM_REF" "$TO_REF"

      - name: Display changed directories
        if: steps.detect-changes.outputs.has_changes == 'true'
        run: |
          echo "The following directories have changes and need to be rebuilt:"
          for dir in ${{ steps.detect-changes.outputs.CHANGED_DIRS }}; do
            echo "- $dir"
          done
